"""Frozen initial production control-plane schema; independent of ORM models."""

import sqlalchemy as sa
from alembic import op

revision = "0001_control_plane"
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "accounts",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("label", sa.String(length=120), nullable=False),
        sa.Column("steam_username", sa.String(length=120), nullable=False),
        sa.Column("email", sa.String(length=320), nullable=True),
        sa.Column("klei_email", sa.String(length=320), nullable=True),
        sa.Column("notes", sa.Text(), nullable=True),
        sa.Column("enabled", sa.Boolean(), nullable=False),
        sa.Column("status", sa.String(length=32), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("steam_username"),
    )
    op.create_table(
        "admin_users",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("username", sa.String(length=120), nullable=False),
        sa.Column("password_hash", sa.Text(), nullable=False),
        sa.Column("enabled", sa.Boolean(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("username"),
    )
    op.create_table(
        "audit_events",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("actor", sa.String(length=120), nullable=False),
        sa.Column("action", sa.String(length=80), nullable=False),
        sa.Column("entity_type", sa.String(length=80), nullable=False),
        sa.Column("entity_id", sa.String(length=120), nullable=False),
        sa.Column("request_id", sa.String(length=64), nullable=True),
        sa.Column("metadata_json", sa.JSON(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_audit_events_action"), "audit_events", ["action"], unique=False
    )
    op.create_index(
        op.f("ix_audit_events_created_at"), "audit_events", ["created_at"], unique=False
    )
    op.create_index(
        op.f("ix_audit_events_request_id"), "audit_events", ["request_id"], unique=False
    )
    op.create_table(
        "nodes",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(length=120), nullable=False),
        sa.Column("provider", sa.String(length=32), nullable=False),
        sa.Column("incus_remote", sa.String(length=255), nullable=True),
        sa.Column("status", sa.String(length=32), nullable=False),
        sa.Column("enabled", sa.Boolean(), nullable=False),
        sa.Column("maintenance", sa.Boolean(), nullable=False),
        sa.Column("draining", sa.Boolean(), nullable=False),
        sa.Column("max_active_slots", sa.Integer(), nullable=False),
        sa.Column("token_hash", sa.String(length=64), nullable=True),
        sa.Column("agent_version", sa.String(length=64), nullable=True),
        sa.Column("last_heartbeat_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("name"),
    )
    op.create_table(
        "runtime_resource_profiles",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(length=120), nullable=False),
        sa.Column("ram_reservation_bytes", sa.BigInteger(), nullable=True),
        sa.Column("cpu_estimate", sa.Float(), nullable=True),
        sa.Column("vram_estimate_bytes", sa.BigInteger(), nullable=True),
        sa.Column("enabled", sa.Boolean(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("name"),
    )
    op.create_table(
        "account_secrets",
        sa.Column("account_id", sa.Integer(), nullable=False),
        sa.Column("steam_password_enc", sa.Text(), nullable=True),
        sa.Column("email_password_enc", sa.Text(), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["account_id"], ["accounts.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("account_id"),
    )
    op.create_table(
        "admin_sessions",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("admin_user_id", sa.Integer(), nullable=False),
        sa.Column("token_hash", sa.String(length=64), nullable=False),
        sa.Column("csrf_hash", sa.String(length=64), nullable=False),
        sa.Column("expires_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("last_seen_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("revoked_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(
            ["admin_user_id"], ["admin_users.id"], ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("token_hash"),
    )
    op.create_index(
        op.f("ix_admin_sessions_admin_user_id"),
        "admin_sessions",
        ["admin_user_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_admin_sessions_expires_at"),
        "admin_sessions",
        ["expires_at"],
        unique=False,
    )
    op.create_index(
        op.f("ix_admin_sessions_revoked_at"),
        "admin_sessions",
        ["revoked_at"],
        unique=False,
    )
    op.create_table(
        "inventory_snapshots",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("account_id", sa.Integer(), nullable=False),
        sa.Column("captured_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("item_count", sa.Integer(), nullable=False),
        sa.Column("raw_metadata", sa.JSON(), nullable=False),
        sa.Column("estimated_value_optional", sa.Float(), nullable=True),
        sa.ForeignKeyConstraint(["account_id"], ["accounts.id"], ondelete="RESTRICT"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_inventory_snapshots_account_id"),
        "inventory_snapshots",
        ["account_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_inventory_snapshots_captured_at"),
        "inventory_snapshots",
        ["captured_at"],
        unique=False,
    )
    op.create_table(
        "node_heartbeats",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("node_id", sa.Integer(), nullable=False),
        sa.Column("agent_version", sa.String(length=64), nullable=False),
        sa.Column("protocol_version", sa.Integer(), nullable=False),
        sa.Column("incus_available", sa.Boolean(), nullable=False),
        sa.Column("active_runtime_count", sa.Integer(), nullable=False),
        sa.Column("received_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["node_id"], ["nodes.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_node_heartbeats_node_id"), "node_heartbeats", ["node_id"], unique=False
    )
    op.create_table(
        "node_resource_snapshots",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("node_id", sa.Integer(), nullable=False),
        sa.Column("cpu_percent", sa.Float(), nullable=True),
        sa.Column("load_1", sa.Float(), nullable=True),
        sa.Column("load_5", sa.Float(), nullable=True),
        sa.Column("load_15", sa.Float(), nullable=True),
        sa.Column("ram_used_bytes", sa.BigInteger(), nullable=True),
        sa.Column("ram_total_bytes", sa.BigInteger(), nullable=True),
        sa.Column("disk_used_bytes", sa.BigInteger(), nullable=True),
        sa.Column("disk_total_bytes", sa.BigInteger(), nullable=True),
        sa.Column("gpu_present", sa.Boolean(), nullable=True),
        sa.Column("gpu_utilization", sa.Float(), nullable=True),
        sa.Column("vram_used_bytes", sa.BigInteger(), nullable=True),
        sa.Column("vram_total_bytes", sa.BigInteger(), nullable=True),
        sa.Column("active_runtime_count", sa.Integer(), nullable=False),
        sa.Column("captured_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["node_id"], ["nodes.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_node_resource_snapshots_captured_at"),
        "node_resource_snapshots",
        ["captured_at"],
        unique=False,
    )
    op.create_index(
        op.f("ix_node_resource_snapshots_node_id"),
        "node_resource_snapshots",
        ["node_id"],
        unique=False,
    )
    op.create_table(
        "runtime_instances",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("account_id", sa.Integer(), nullable=False),
        sa.Column("node_id", sa.Integer(), nullable=False),
        sa.Column("provider", sa.String(length=32), nullable=False),
        sa.Column("external_id", sa.String(length=255), nullable=False),
        sa.Column("state", sa.String(length=32), nullable=False),
        sa.Column("desired_state", sa.String(length=32), nullable=False),
        sa.Column("network_profile", sa.String(length=120), nullable=True),
        sa.Column("runtime_generation", sa.Integer(), nullable=False),
        sa.Column("image_version", sa.String(length=120), nullable=False),
        sa.Column("active", sa.Boolean(), nullable=False),
        sa.Column("command_version", sa.Integer(), nullable=False),
        sa.Column("token_hash", sa.String(length=64), nullable=True),
        sa.Column("agent_version", sa.String(length=64), nullable=True),
        sa.Column("last_error_code", sa.String(length=64), nullable=True),
        sa.Column("last_error_message", sa.Text(), nullable=True),
        sa.Column("last_heartbeat_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["account_id"], ["accounts.id"], ondelete="RESTRICT"),
        sa.ForeignKeyConstraint(["node_id"], ["nodes.id"], ondelete="RESTRICT"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "account_id", "runtime_generation", name="uq_runtime_account_generation"
        ),
        sa.UniqueConstraint("external_id"),
    )
    op.create_index(
        op.f("ix_runtime_instances_account_id"),
        "runtime_instances",
        ["account_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_runtime_instances_node_id"),
        "runtime_instances",
        ["node_id"],
        unique=False,
    )
    op.create_index(
        "uq_runtime_one_active_per_account",
        "runtime_instances",
        ["account_id"],
        unique=True,
        sqlite_where=sa.text("active = 1"),
        postgresql_where=sa.text("active = true"),
    )
    op.create_table(
        "events",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("account_id", sa.Integer(), nullable=True),
        sa.Column("runtime_id", sa.Integer(), nullable=True),
        sa.Column("node_id", sa.Integer(), nullable=True),
        sa.Column("level", sa.String(length=16), nullable=False),
        sa.Column("kind", sa.String(length=80), nullable=False),
        sa.Column("message", sa.Text(), nullable=False),
        sa.Column("metadata_json", sa.JSON(), nullable=False),
        sa.Column("request_id", sa.String(length=64), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["account_id"], ["accounts.id"], ondelete="SET NULL"),
        sa.ForeignKeyConstraint(["node_id"], ["nodes.id"], ondelete="SET NULL"),
        sa.ForeignKeyConstraint(
            ["runtime_id"], ["runtime_instances.id"], ondelete="SET NULL"
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_events_account_id"), "events", ["account_id"], unique=False
    )
    op.create_index(
        op.f("ix_events_created_at"), "events", ["created_at"], unique=False
    )
    op.create_index(op.f("ix_events_kind"), "events", ["kind"], unique=False)
    op.create_index(op.f("ix_events_level"), "events", ["level"], unique=False)
    op.create_index(op.f("ix_events_node_id"), "events", ["node_id"], unique=False)
    op.create_index(
        op.f("ix_events_request_id"), "events", ["request_id"], unique=False
    )
    op.create_index(
        op.f("ix_events_runtime_id"), "events", ["runtime_id"], unique=False
    )
    op.create_table(
        "jobs",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("kind", sa.String(length=40), nullable=False),
        sa.Column("account_id", sa.Integer(), nullable=True),
        sa.Column("runtime_id", sa.Integer(), nullable=True),
        sa.Column("node_id", sa.Integer(), nullable=True),
        sa.Column("status", sa.String(length=20), nullable=False),
        sa.Column("priority", sa.Integer(), nullable=False),
        sa.Column("attempt_count", sa.Integer(), nullable=False),
        sa.Column("max_attempts", sa.Integer(), nullable=False),
        sa.Column("run_after", sa.DateTime(timezone=True), nullable=False),
        sa.Column("leased_until", sa.DateTime(timezone=True), nullable=True),
        sa.Column("lease_owner", sa.String(length=120), nullable=True),
        sa.Column("idempotency_key", sa.String(length=255), nullable=False),
        sa.Column("request_id", sa.String(length=64), nullable=True),
        sa.Column("payload", sa.JSON(), nullable=False),
        sa.Column("last_error_code", sa.String(length=64), nullable=True),
        sa.Column("last_error", sa.Text(), nullable=True),
        sa.Column("started_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("completed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["account_id"], ["accounts.id"], ondelete="SET NULL"),
        sa.ForeignKeyConstraint(["node_id"], ["nodes.id"], ondelete="SET NULL"),
        sa.ForeignKeyConstraint(
            ["runtime_id"], ["runtime_instances.id"], ondelete="SET NULL"
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("idempotency_key"),
    )
    op.create_index(op.f("ix_jobs_account_id"), "jobs", ["account_id"], unique=False)
    op.create_index(op.f("ix_jobs_kind"), "jobs", ["kind"], unique=False)
    op.create_index(
        op.f("ix_jobs_leased_until"), "jobs", ["leased_until"], unique=False
    )
    op.create_index(op.f("ix_jobs_node_id"), "jobs", ["node_id"], unique=False)
    op.create_index(op.f("ix_jobs_request_id"), "jobs", ["request_id"], unique=False)
    op.create_index(op.f("ix_jobs_run_after"), "jobs", ["run_after"], unique=False)
    op.create_index(op.f("ix_jobs_runtime_id"), "jobs", ["runtime_id"], unique=False)
    op.create_index(op.f("ix_jobs_status"), "jobs", ["status"], unique=False)
    op.create_index(
        "uq_job_active_command",
        "jobs",
        ["runtime_id", "kind"],
        unique=True,
        sqlite_where=sa.text("status IN ('PENDING','LEASED','RUNNING','RETRY')"),
        postgresql_where=sa.text("status IN ('PENDING','LEASED','RUNNING','RETRY')"),
    )
    op.create_table(
        "runs",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("account_id", sa.Integer(), nullable=False),
        sa.Column("runtime_id", sa.Integer(), nullable=False),
        sa.Column("node_id", sa.Integer(), nullable=False),
        sa.Column("started_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("ended_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("duration_seconds", sa.Integer(), nullable=True),
        sa.Column("result", sa.String(length=40), nullable=True),
        sa.Column("start_reason", sa.String(length=80), nullable=False),
        sa.Column("error_code", sa.String(length=64), nullable=True),
        sa.ForeignKeyConstraint(["account_id"], ["accounts.id"], ondelete="RESTRICT"),
        sa.ForeignKeyConstraint(["node_id"], ["nodes.id"], ondelete="RESTRICT"),
        sa.ForeignKeyConstraint(
            ["runtime_id"], ["runtime_instances.id"], ondelete="RESTRICT"
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_runs_account_id"), "runs", ["account_id"], unique=False)
    op.create_index(op.f("ix_runs_node_id"), "runs", ["node_id"], unique=False)
    op.create_index(op.f("ix_runs_runtime_id"), "runs", ["runtime_id"], unique=False)
    op.create_table(
        "runtime_heartbeats",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("runtime_id", sa.Integer(), nullable=False),
        sa.Column("phase", sa.String(length=80), nullable=False),
        sa.Column("steam_running", sa.Boolean(), nullable=False),
        sa.Column("dst_running", sa.Boolean(), nullable=False),
        sa.Column("healthy", sa.Boolean(), nullable=False),
        sa.Column("agent_version", sa.String(length=64), nullable=False),
        sa.Column("protocol_version", sa.Integer(), nullable=False),
        sa.Column("received_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["runtime_id"], ["runtime_instances.id"], ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_runtime_heartbeats_runtime_id"),
        "runtime_heartbeats",
        ["runtime_id"],
        unique=False,
    )
    op.create_table(
        "runtime_view_sessions",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("runtime_id", sa.Integer(), nullable=False),
        sa.Column("created_by", sa.String(length=120), nullable=False),
        sa.Column("token_hash", sa.String(length=64), nullable=False),
        sa.Column("status", sa.String(length=32), nullable=False),
        sa.Column("expires_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("closed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["runtime_id"], ["runtime_instances.id"], ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("token_hash"),
    )
    op.create_index(
        op.f("ix_runtime_view_sessions_expires_at"),
        "runtime_view_sessions",
        ["expires_at"],
        unique=False,
    )
    op.create_index(
        op.f("ix_runtime_view_sessions_runtime_id"),
        "runtime_view_sessions",
        ["runtime_id"],
        unique=False,
    )
    op.create_table(
        "worker_status",
        sa.Column("runtime_id", sa.Integer(), nullable=False),
        sa.Column("phase", sa.String(length=80), nullable=False),
        sa.Column("steam_running", sa.Boolean(), nullable=False),
        sa.Column("dst_running", sa.Boolean(), nullable=False),
        sa.Column("healthy", sa.Boolean(), nullable=False),
        sa.Column("automation_state", sa.String(length=80), nullable=False),
        sa.Column("details", sa.JSON(), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["runtime_id"], ["runtime_instances.id"], ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("runtime_id"),
    )
    op.create_table(
        "job_attempts",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("job_id", sa.Integer(), nullable=False),
        sa.Column("attempt_number", sa.Integer(), nullable=False),
        sa.Column("worker_id", sa.String(length=120), nullable=False),
        sa.Column("status", sa.String(length=20), nullable=False),
        sa.Column("error_code", sa.String(length=64), nullable=True),
        sa.Column("error_message", sa.Text(), nullable=True),
        sa.Column("started_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("completed_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(["job_id"], ["jobs.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("job_id", "attempt_number", name="uq_job_attempt_number"),
    )
    op.create_index(
        op.f("ix_job_attempts_job_id"), "job_attempts", ["job_id"], unique=False
    )
    op.create_table(
        "runtime_leases",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("node_id", sa.Integer(), nullable=False),
        sa.Column("runtime_id", sa.Integer(), nullable=False),
        sa.Column("lease_type", sa.String(length=32), nullable=False),
        sa.Column("lease_token", sa.String(length=64), nullable=False),
        sa.Column("job_id", sa.Integer(), nullable=True),
        sa.Column("leased_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("expires_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("released_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(["job_id"], ["jobs.id"], ondelete="SET NULL"),
        sa.ForeignKeyConstraint(["node_id"], ["nodes.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(
            ["runtime_id"], ["runtime_instances.id"], ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("lease_token"),
    )
    op.create_index(
        op.f("ix_runtime_leases_expires_at"),
        "runtime_leases",
        ["expires_at"],
        unique=False,
    )
    op.create_index(
        op.f("ix_runtime_leases_job_id"), "runtime_leases", ["job_id"], unique=False
    )
    op.create_index(
        op.f("ix_runtime_leases_node_id"), "runtime_leases", ["node_id"], unique=False
    )
    op.create_index(
        op.f("ix_runtime_leases_released_at"),
        "runtime_leases",
        ["released_at"],
        unique=False,
    )
    op.create_index(
        op.f("ix_runtime_leases_runtime_id"),
        "runtime_leases",
        ["runtime_id"],
        unique=False,
    )
    op.create_index(
        "uq_runtime_active_slot_lease",
        "runtime_leases",
        ["runtime_id"],
        unique=True,
        sqlite_where=sa.text("released_at IS NULL"),
        postgresql_where=sa.text("released_at IS NULL"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        "uq_runtime_active_slot_lease",
        table_name="runtime_leases",
        sqlite_where=sa.text("released_at IS NULL"),
        postgresql_where=sa.text("released_at IS NULL"),
    )
    op.drop_index(op.f("ix_runtime_leases_runtime_id"), table_name="runtime_leases")
    op.drop_index(op.f("ix_runtime_leases_released_at"), table_name="runtime_leases")
    op.drop_index(op.f("ix_runtime_leases_node_id"), table_name="runtime_leases")
    op.drop_index(op.f("ix_runtime_leases_job_id"), table_name="runtime_leases")
    op.drop_index(op.f("ix_runtime_leases_expires_at"), table_name="runtime_leases")
    op.drop_table("runtime_leases")
    op.drop_index(op.f("ix_job_attempts_job_id"), table_name="job_attempts")
    op.drop_table("job_attempts")
    op.drop_table("worker_status")
    op.drop_index(
        op.f("ix_runtime_view_sessions_runtime_id"), table_name="runtime_view_sessions"
    )
    op.drop_index(
        op.f("ix_runtime_view_sessions_expires_at"), table_name="runtime_view_sessions"
    )
    op.drop_table("runtime_view_sessions")
    op.drop_index(
        op.f("ix_runtime_heartbeats_runtime_id"), table_name="runtime_heartbeats"
    )
    op.drop_table("runtime_heartbeats")
    op.drop_index(op.f("ix_runs_runtime_id"), table_name="runs")
    op.drop_index(op.f("ix_runs_node_id"), table_name="runs")
    op.drop_index(op.f("ix_runs_account_id"), table_name="runs")
    op.drop_table("runs")
    op.drop_index(
        "uq_job_active_command",
        table_name="jobs",
        sqlite_where=sa.text("status IN ('PENDING','LEASED','RUNNING','RETRY')"),
        postgresql_where=sa.text("status IN ('PENDING','LEASED','RUNNING','RETRY')"),
    )
    op.drop_index(op.f("ix_jobs_status"), table_name="jobs")
    op.drop_index(op.f("ix_jobs_runtime_id"), table_name="jobs")
    op.drop_index(op.f("ix_jobs_run_after"), table_name="jobs")
    op.drop_index(op.f("ix_jobs_request_id"), table_name="jobs")
    op.drop_index(op.f("ix_jobs_node_id"), table_name="jobs")
    op.drop_index(op.f("ix_jobs_leased_until"), table_name="jobs")
    op.drop_index(op.f("ix_jobs_kind"), table_name="jobs")
    op.drop_index(op.f("ix_jobs_account_id"), table_name="jobs")
    op.drop_table("jobs")
    op.drop_index(op.f("ix_events_runtime_id"), table_name="events")
    op.drop_index(op.f("ix_events_request_id"), table_name="events")
    op.drop_index(op.f("ix_events_node_id"), table_name="events")
    op.drop_index(op.f("ix_events_level"), table_name="events")
    op.drop_index(op.f("ix_events_kind"), table_name="events")
    op.drop_index(op.f("ix_events_created_at"), table_name="events")
    op.drop_index(op.f("ix_events_account_id"), table_name="events")
    op.drop_table("events")
    op.drop_index(
        "uq_runtime_one_active_per_account",
        table_name="runtime_instances",
        sqlite_where=sa.text("active = 1"),
        postgresql_where=sa.text("active = true"),
    )
    op.drop_index(op.f("ix_runtime_instances_node_id"), table_name="runtime_instances")
    op.drop_index(
        op.f("ix_runtime_instances_account_id"), table_name="runtime_instances"
    )
    op.drop_table("runtime_instances")
    op.drop_index(
        op.f("ix_node_resource_snapshots_node_id"), table_name="node_resource_snapshots"
    )
    op.drop_index(
        op.f("ix_node_resource_snapshots_captured_at"),
        table_name="node_resource_snapshots",
    )
    op.drop_table("node_resource_snapshots")
    op.drop_index(op.f("ix_node_heartbeats_node_id"), table_name="node_heartbeats")
    op.drop_table("node_heartbeats")
    op.drop_index(
        op.f("ix_inventory_snapshots_captured_at"), table_name="inventory_snapshots"
    )
    op.drop_index(
        op.f("ix_inventory_snapshots_account_id"), table_name="inventory_snapshots"
    )
    op.drop_table("inventory_snapshots")
    op.drop_index(op.f("ix_admin_sessions_revoked_at"), table_name="admin_sessions")
    op.drop_index(op.f("ix_admin_sessions_expires_at"), table_name="admin_sessions")
    op.drop_index(op.f("ix_admin_sessions_admin_user_id"), table_name="admin_sessions")
    op.drop_table("admin_sessions")
    op.drop_table("account_secrets")
    op.drop_table("runtime_resource_profiles")
    op.drop_table("nodes")
    op.drop_index(op.f("ix_audit_events_request_id"), table_name="audit_events")
    op.drop_index(op.f("ix_audit_events_created_at"), table_name="audit_events")
    op.drop_index(op.f("ix_audit_events_action"), table_name="audit_events")
    op.drop_table("audit_events")
    op.drop_table("admin_users")
    op.drop_table("accounts")
    # ### end Alembic commands ###
